### ISSUE TITLE
A USER ERROR has occurred: Traversal by intervals was requested but some input files are not indexed.

### ISSUE THREAD

**Issue by LeonMaiShi** [gatk-workflows/gatk4-exome-analysis-pipeline#3]
Hi GATK Team,

First of all, thank you for providing this nice pipeline for the community. I have applied this pipeline to analyze my own WES data. However, the workflow failed due to the captioned error. The complete error information is
```
***********************************************************************

A USER ERROR has occurred: Traversal by intervals was requested but some input files are not indexed.
Please index all input files:

samtools index /cromwell-executions/ExomeGermlineSingleSample/d39350df-8128-4007-99ed-43a3414fa185/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/2e1bd164-dc05-413f-a118-6c39e80cd032/call-BaseRecalibrator/shard-7/inputs/98696239/H
HH.GRCh38DH.exome.aligned.duplicate_marked.sorted.bam


***********************************************************************
```
and
```
[error] WorkflowManagerActor Workflow d39350df-8128-4007-99ed-43a3414fa185 failed (during ExecutingWorkflowState): Job UnmappedBamToAlignedBam.BaseRecalibrator:7:1 exited with return code 2 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
```
Given that these errrors suggested there are something wrong with `BaseRecalibrator`, I investigated the two result folders: `call-SortSampleBam` and `call-BaseRecalibrator`. What I have found is that those index files obtained from the `SortSampleBam` step had not been included in the `inputs` folder of the `BaseRecalibrator` step. This explains the error. 
To further understand why those index files were lost, I dug into the `.wdl` files of this pipeline. I quickly identified a problematic part in the [BamProcessing.wdl](https://github.com/gatk-workflows/gatk4-exome-analysis-pipeline/blob/master/tasks/BamProcessing.wdl) as follows:
```
# Generate Base Quality Score Recalibration (BQSR) model
task BaseRecalibrator {
  input {
    File input_bam
    String recalibration_report_filename
    Array[String] sequence_group_interval
...
```
As a benchmark, I looked back at another best-practice workflow that I have previously applied to my data successfully: [gatk4-data-processing/processing-for-variant-discovery-gatk4.wdl](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl). The codes of the same function, however, is:
```
# Generate Base Quality Score Recalibration (BQSR) model
task BaseRecalibrator {
  File input_bam
  File input_bam_index
  String recalibration_report_filename
  Array[String] sequence_group_interval
```
Do you see the difference? I highly suspect that it is the missing of `File input_bam_index` that leads to the error I have come across. I will test my hypothesis by adding this statement back to the code of `BamProcessing.wdl`, and see whether the same errors remain. Since I am a newbie to GATK, can anyone tell me whether or why the `BaseRecalibrator` should be coded in this way for exome data analysis?

Thanks,
Leon

**Comment by bshifaw** [comment]
Hi @LeonMaiShi ,

This question would be best answered on the [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) or [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team). Also include how you are running the workflow (locally or on google cloud platform) and what version of gatk your are using.
You can view document info on BaseRecalibrator in the Tool docs can be located [here](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_bqsr_BaseRecalibrator.php). 

I spoke with some colleagues and the answer yes, the code that was written is intentional. The workflow was written to work on Google Cloud Platform which would allow cromwell and gatk can assume and access the index file. Your proposed solution should work, you may also want to add a line in the parameter_meta block of that task for the input_bam_index. Also other tasks would be need to be edited (applyrecal, haplotypecaller )

```
  parameter_meta {
    input_bam: {
      localization_optional: true
    }
```


  
Thanks

**Comment by LeonMaiShi** [comment]
Hi @bshifaw ,

Many thanks for your reply and suggestions! I had tested the workflow locally using the latest GATK4. I had not realized that I should modify those .wdl files either besides the .inputs.json. After including the line of input_bam_index to those tasks that require it, I had the workflow finished properly.

Thanks,
Leon
